### PR TITLE
separate requestPermissions and registerVoipToken

### PR DESCRIPTION
**Pull request by r0b0t3d**
#39

### CODE REVIEW

**Comment by lonnylot** [comment]
ping @zxcpoiu any chance of getting this merged in? It works better for some flows to request permission and register the token separately. Primarily where we need to handle regular push notifications separately...

**Comment by zxcpoiu** [comment]
Thanks for ping.

I agree with this change as well, since it is more accurate.

It seems a bit breaking change, the usage would be:

### original: 

```
VoipPushNotification.requestPermissions(); // required
```

### after: 

```
VoipPushNotification.requestPermissions(); // required
VoipPushNotification.registerVoipToken(); // required
```

is it correct?

**Comment by r0b0t3d** [comment]
@zxcpoiu 
```
VoipPushNotification.requestPermissions(); // **optional** user can use other libs to ask for notification permission.

VoipPushNotification.registerVoipToken(); // **required** to get voip token
```

**Comment by lonnylot** [comment]
I'd be in favor of keeping `requestPermissions` the way it is and adding `registerVoipToken`. That way we don't break backwards compatibility and we can get the functionality we desire.

**Comment by r0b0t3d** [comment]
@lonnylot I'm fine with it
@zxcpoiu how do you think?

**Comment by zxcpoiu** [comment]
Hmm... both has pros and cons.

It's a bit ambiguous that `requestPermissions` implicitly invoke `registerVoipToken` when we have both functionalities.

Is there any use case which request permissions independently? ( invoke register later at some point  )
If so, it's better do a breaking change.

**Comment by r0b0t3d** [comment]
@zxcpoiu 
1. `registerVoipToken` does not require notification permission. so it is fine when calling separately.
2. If user use another lib for local notification (like `react-native-firebase`, `react-native-push-notification`, ...), they don't need to call `requestPermissions` anymore.

**Comment by zxcpoiu** [comment]
Thanks!

It would be clearer that `requestPermission` just do request permissions instead register voip token at the same time.

While we need to release a breaking release for pod file, so I prefer to make api clearer while we are at it. :)

**Pull request merged**
